# File: .github/rulesets/main-branch-rules.yml
name: Main Branch Protection
target: branch
enforcement: active
conditions:
  - ref_name:
      include:
        - main
rules:
  - type: deletion
    parameters: {}
  - type: non_fast_forward
    parameters: {}
  - type: pull_request
    parameters:
      required_approving_review_count: 1
      require_code_owner_reviews: true
      required_review_thread_resolution: true
  - type: required_status_checks
    parameters:
      required_status_checks:
        - context: "Test Extension"
        - context: "Publish Extension"
      strict_required_status_checks_policy: true